variable "account_id" {
  description = "Cloudflare account ID hosting the catalog R2 bucket."
  type        = string
  sensitive   = true
}

variable "zone_id_opennutritracker_org" {
  description = "Cloudflare zone ID for opennutritracker.org. Scope for the cache rule and the cache-purge API token."
  type        = string
  sensitive   = true
}

variable "edge_cache_seconds" {
  description = "How long the catalog .db.gz files stay cached at the edge."
  type        = number
}

variable "browser_cache_seconds" {
  description = "How long client browsers can hold catalog .db.gz files."
  type        = number
}

variable "catalog_host" {
  description = "Public host the WAF Custom Rule matches on. Equal to the R2 custom-domain output but threaded as a variable so the rule and the bucket can be reasoned about independently."
  type        = string
  default     = "catalog.opennutritracker.org"
}

variable "catalog_access_token" {
  description = "Shared bearer token clients must present in the X-Catalog-Access header. Generated by the root random_password.catalog_access_token resource and passed in here as a sensitive value; the rule expression interpolates it into the wirefilter match. Long-lived by design — rotation is emergency-only and requires a fresh APK build to ship the new value via envied."
  type        = string
  sensitive   = true
}
